# action.yml
name: 'Update Partner Center offer artifact'
description: 'Update Partner Center offer artifact'
inputs:
  offerName:
    description: 'Offer name'
    required: true
  planName:
    description: 'Plan name'
    required: true
  filePath:
    description: 'Artifact file path'
    required: false
  artifactVersion:
    description: 'Artifact version'
    required: false
    default: '1.0.0'
  clientId:
    description: "client id"
    required: true
    default: 'invalid'
  secretValue:
    description: "secret value"
    required: true
    default: 'invalid'
  tenantId:
    description: "tenant id"
    required: true
    default: 'invalid'
  offerType:
    description: "offer type"
    required: true
    default: 'invalid'
  imageVersionNumber:
    description: "image version number"
    required: false
    default: 'invalid'
  imageType:
    description: "image type"
    required: false
    default: 'invalid'
  osDiskSasUrl:
    description: "OS Disk SAS URL"
    required: false
    default: 'invalid'
  dataDiskSasUrl:
    description: "Data Disk SAS URL"
    required: false
    default: 'invalid'
  operatingSystemFamily:
    description: "The OS family name"
    required: false
    default: 'invalid'
  operatingSystemType:
    description: "The OS type name"
    required: false
    default: 'invalid'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.offerName }} 
    - ${{ inputs.planName }} 
    - ${{ inputs.filePath }} 
    - ${{ inputs.artifactVersion }}
    - ${{ inputs.clientId }}
    - ${{ inputs.secretValue }}
    - ${{ inputs.tenantId }}
    - ${{ inputs.offerType }}
    - ${{ inputs.imageVersionNumber }}
    - ${{ inputs.imageType }}
    - ${{ inputs.osDiskSasUrl }}
    - ${{ inputs.dataDiskSasUrl }}
    - ${{ inputs.operatingSystemFamily }}
    - ${{ inputs.operatingSystemType }}